// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbic0q5but8tU1O1gCe70GF1C4L4VAz2I',
    appId: '1:929878449130:web:7efd28fcb9e26857f4f093',
    messagingSenderId: '929878449130',
    projectId: 'devera-news-app',
    authDomain: 'devera-news-app.firebaseapp.com',
    storageBucket: 'devera-news-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaX7alRLQwOkCMLUQbP0EeOxK6Un0emvo',
    appId: '1:929878449130:android:0da45a7eb134fef1f4f093',
    messagingSenderId: '929878449130',
    projectId: 'devera-news-app',
    storageBucket: 'devera-news-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6SfhEG_7S_Xw-2edOyTsqNCWqMLYipaw',
    appId: '1:929878449130:ios:5bf9dec2f090ac22f4f093',
    messagingSenderId: '929878449130',
    projectId: 'devera-news-app',
    storageBucket: 'devera-news-app.appspot.com',
    iosBundleId: 'com.example.deveraNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6SfhEG_7S_Xw-2edOyTsqNCWqMLYipaw',
    appId: '1:929878449130:ios:dd722e31aa610476f4f093',
    messagingSenderId: '929878449130',
    projectId: 'devera-news-app',
    storageBucket: 'devera-news-app.appspot.com',
    iosBundleId: 'com.example.deveraNewsApp.RunnerTests',
  );
}
